site_name: PwnLand
site_url: https://pwnfuzz.github.io/PwnLand/
repo_url: https://github.com/PwnFuzz/PwnLand
repo_name: PwnFuzz/PwnLand

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Buffer Overflows: BufferOverflows/index.md
  - Heap Exploitation:
    - GLIBC 2.23: Heap/GLIBC-2.23.md
    - GLIBC 2.27: Heap/GLIBC-2.27.md
  - CTF Writeups: CTFs/index.md

plugins:
  - search